apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adeptus.fullname" . }}-secrets
  labels:
    {{- include "adeptus.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- if .Values.secrets.cdnApiKey }}
  cdn-api-key: {{ .Values.secrets.cdnApiKey | b64enc | quote }}
  {{- end }}
